# Generated by Django 5.2.4 on 2025-08-06 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('quadrante', models.CharField(choices=[('MUDAR', 'Mudar'), ('OBJETIVO', 'Objetivo'), ('FAZER_FLUIR', 'Fazer Fluir'), ('FAZER_MELHOR', 'Fazer Melhor')], max_length=20)),
                ('peso', models.FloatField(default=1.0)),
                ('ordem', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('coordenada_x', models.FloatField()),
                ('coordenada_y', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.pergunta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
